services:
  db:
    image: postgres
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    command: -p 5432
    volumes:
      - ${PATH_TO_STORAGE}:/var/lib/postgresql/data/:rw
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: root
      PGDATA : /var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
  blazorapp:
    image: blazorapp
    ports:
      - "50045:8080"
    build:
      context: .
      dockerfile: BlazorApp/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    command: [ "python", "app.py" ]  
  blazorappapi:
    image: blazorappapi
    build:
      context: .
      dockerfile: BlazorAppApi/Dockerfile
    ports: # <-- ADD THIS BLOCK
      - "5001:8080" # Maps host machine port 5001 to container port 8080
