services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ${PATH_TO_STORAGE}:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
  
  blazorapp:
    image: blazorapp
    ports:
      - "5000:8080"
    build:
      context: .
      dockerfile: BlazorApp/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    command: [ "python", "app.py" ]
    
  blazorappapi:
    image: blazorappapi
    build:
      context: .
      dockerfile: BlazorAppApi/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    command: [ "python", "app.py" ]
    ports:
      - "5001:8080"
    volumes:
      - dpkeys:/app/keys/
  
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.7
    volumes:
      - "./keycloak:/opt/keycloak/data/import"
    ports:
      - "8082:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB: postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    depends_on:
      db:
        condition: service_healthy
    command: ["start-dev", "--import-realm"]
volumes:
  dpkeys: {}