// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SharedModelDbContext;

#nullable disable

namespace SharedModelDbContext.Entities
{
    [DbContext(typeof(BlazorQuestDbContext))]
    [Migration("20251123202310_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("DonjonsSalles", b =>
                {
                    b.Property<int>("donjonsListdonjonsid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("sallesListsalleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("donjonsListdonjonsid", "sallesListsalleId");

                    b.HasIndex("sallesListsalleId");

                    b.ToTable("DonjonsSalles");
                });

            modelBuilder.Entity("SharedModels.Administrateur", b =>
                {
                    b.Property<int>("administrateurid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("utilisateurId")
                        .HasColumnType("INTEGER");

                    b.HasKey("administrateurid");

                    b.HasIndex("utilisateurId")
                        .IsUnique();

                    b.ToTable("Administrateurs");
                });

            modelBuilder.Entity("SharedModels.Donjons", b =>
                {
                    b.Property<int>("donjonsid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("donjonsid");

                    b.ToTable("DonjonsEnumerable");
                });

            modelBuilder.Entity("SharedModels.Joueur", b =>
                {
                    b.Property<int>("joueurid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("utilisateurId")
                        .HasColumnType("INTEGER");

                    b.HasKey("joueurid");

                    b.HasIndex("utilisateurId")
                        .IsUnique();

                    b.ToTable("Joueurs");
                });

            modelBuilder.Entity("SharedModels.Monstre", b =>
                {
                    b.Property<int>("monstreid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("salleid")
                        .HasColumnType("INTEGER");

                    b.HasKey("monstreid");

                    b.HasIndex("salleid")
                        .IsUnique();

                    b.ToTable("Monstres");
                });

            modelBuilder.Entity("SharedModels.Salles", b =>
                {
                    b.Property<int>("salleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("salleId");

                    b.ToTable("SallesEnumerable");
                });

            modelBuilder.Entity("SharedModels.ScorePartie", b =>
                {
                    b.Property<int>("joueurId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("score")
                        .HasColumnType("INTEGER");

                    b.HasKey("joueurId");

                    b.ToTable("ScoreParties");
                });

            modelBuilder.Entity("SharedModels.Utilisateur", b =>
                {
                    b.Property<int>("utilisateurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("adresseMail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("motDePasse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("utilisateurId");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("DonjonsSalles", b =>
                {
                    b.HasOne("SharedModels.Donjons", null)
                        .WithMany()
                        .HasForeignKey("donjonsListdonjonsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedModels.Salles", null)
                        .WithMany()
                        .HasForeignKey("sallesListsalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharedModels.Administrateur", b =>
                {
                    b.HasOne("SharedModels.Utilisateur", "Utilisateur")
                        .WithOne("administrateur")
                        .HasForeignKey("SharedModels.Administrateur", "utilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("SharedModels.Joueur", b =>
                {
                    b.HasOne("SharedModels.Utilisateur", "utilisateur")
                        .WithOne("joueur")
                        .HasForeignKey("SharedModels.Joueur", "utilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("utilisateur");
                });

            modelBuilder.Entity("SharedModels.Monstre", b =>
                {
                    b.HasOne("SharedModels.Salles", "salle")
                        .WithOne("monstre")
                        .HasForeignKey("SharedModels.Monstre", "salleid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("salle");
                });

            modelBuilder.Entity("SharedModels.ScorePartie", b =>
                {
                    b.HasOne("SharedModels.Joueur", "joueur")
                        .WithOne("score")
                        .HasForeignKey("SharedModels.ScorePartie", "joueurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("joueur");
                });

            modelBuilder.Entity("SharedModels.Joueur", b =>
                {
                    b.Navigation("score");
                });

            modelBuilder.Entity("SharedModels.Salles", b =>
                {
                    b.Navigation("monstre");
                });

            modelBuilder.Entity("SharedModels.Utilisateur", b =>
                {
                    b.Navigation("administrateur");

                    b.Navigation("joueur");
                });
#pragma warning restore 612, 618
        }
    }
}
