// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SharedModelDbContext;

#nullable disable

namespace SharedModelDbContext.Entities
{
    [DbContext(typeof(BlazorQuestDbContext))]
    [Migration("20251124214001_AjoutDesAttributsDeMonstre")]
    partial class AjoutDesAttributsDeMonstre
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("blazorgame")
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DonjonsSalles", b =>
                {
                    b.Property<int>("donjonsListdonjonsid")
                        .HasColumnType("integer");

                    b.Property<int>("sallesListsalleId")
                        .HasColumnType("integer");

                    b.HasKey("donjonsListdonjonsid", "sallesListsalleId");

                    b.HasIndex("sallesListsalleId");

                    b.ToTable("DonjonsSalles", "blazorgame");
                });

            modelBuilder.Entity("SharedModels.Administrateur", b =>
                {
                    b.Property<int>("administrateurid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("administrateurid"));

                    b.Property<int>("utilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("administrateurid");

                    b.HasIndex("utilisateurId")
                        .IsUnique();

                    b.ToTable("Administrateurs", "blazorgame");
                });

            modelBuilder.Entity("SharedModels.Donjons", b =>
                {
                    b.Property<int>("donjonsid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("donjonsid"));

                    b.HasKey("donjonsid");

                    b.ToTable("DonjonsEnumerable", "blazorgame");
                });

            modelBuilder.Entity("SharedModels.Joueur", b =>
                {
                    b.Property<int>("joueurid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("joueurid"));

                    b.Property<int>("utilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("joueurid");

                    b.HasIndex("utilisateurId")
                        .IsUnique();

                    b.ToTable("Joueurs", "blazorgame");
                });

            modelBuilder.Entity("SharedModels.Monstre", b =>
                {
                    b.Property<int>("monstreid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("monstreid"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("salleid")
                        .HasColumnType("integer");

                    b.HasKey("monstreid");

                    b.HasIndex("salleid")
                        .IsUnique();

                    b.ToTable("Monstres", "blazorgame");
                });

            modelBuilder.Entity("SharedModels.Salles", b =>
                {
                    b.Property<int>("salleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("salleId"));

                    b.HasKey("salleId");

                    b.ToTable("SallesEnumerable", "blazorgame");
                });

            modelBuilder.Entity("SharedModels.ScorePartie", b =>
                {
                    b.Property<int>("joueurId")
                        .HasColumnType("integer");

                    b.Property<int>("score")
                        .HasColumnType("integer");

                    b.HasKey("joueurId");

                    b.ToTable("ScoreParties", "blazorgame");
                });

            modelBuilder.Entity("SharedModels.Utilisateur", b =>
                {
                    b.Property<int>("utilisateurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("utilisateurId"));

                    b.Property<string>("adresseMail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("motDePasse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("utilisateurId");

                    b.ToTable("Utilisateurs", "blazorgame");
                });

            modelBuilder.Entity("DonjonsSalles", b =>
                {
                    b.HasOne("SharedModels.Donjons", null)
                        .WithMany()
                        .HasForeignKey("donjonsListdonjonsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedModels.Salles", null)
                        .WithMany()
                        .HasForeignKey("sallesListsalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharedModels.Administrateur", b =>
                {
                    b.HasOne("SharedModels.Utilisateur", "utilisateur")
                        .WithOne("administrateur")
                        .HasForeignKey("SharedModels.Administrateur", "utilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("utilisateur");
                });

            modelBuilder.Entity("SharedModels.Joueur", b =>
                {
                    b.HasOne("SharedModels.Utilisateur", "utilisateur")
                        .WithOne("joueur")
                        .HasForeignKey("SharedModels.Joueur", "utilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("utilisateur");
                });

            modelBuilder.Entity("SharedModels.Monstre", b =>
                {
                    b.HasOne("SharedModels.Salles", "salle")
                        .WithOne("monstre")
                        .HasForeignKey("SharedModels.Monstre", "salleid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("salle");
                });

            modelBuilder.Entity("SharedModels.ScorePartie", b =>
                {
                    b.HasOne("SharedModels.Joueur", "joueur")
                        .WithOne("score")
                        .HasForeignKey("SharedModels.ScorePartie", "joueurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("joueur");
                });

            modelBuilder.Entity("SharedModels.Joueur", b =>
                {
                    b.Navigation("score");
                });

            modelBuilder.Entity("SharedModels.Salles", b =>
                {
                    b.Navigation("monstre");
                });

            modelBuilder.Entity("SharedModels.Utilisateur", b =>
                {
                    b.Navigation("administrateur");

                    b.Navigation("joueur");
                });
#pragma warning restore 612, 618
        }
    }
}
