// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SharedModelDbContext;

#nullable disable

namespace SharedModelDbContext.Entities
{
    [DbContext(typeof(BlazorQuestDbContext))]
    [Migration("20251208224734_s")]
    partial class s
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("blazorgame")
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DonjonsSalles", b =>
                {
                    b.Property<int>("donjonsListdonjonsid")
                        .HasColumnType("integer");

                    b.Property<int>("sallesListsalleId")
                        .HasColumnType("integer");

                    b.HasKey("donjonsListdonjonsid", "sallesListsalleId");

                    b.HasIndex("sallesListsalleId");

                    b.ToTable("DonjonsSalles", "blazorgame");
                });

            modelBuilder.Entity("SharedModels.Administrateur", b =>
                {
                    b.Property<int>("administrateurid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("administrateurid"));

                    b.Property<int>("utilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("administrateurid");

                    b.HasIndex("utilisateurId")
                        .IsUnique();

                    b.ToTable("Administrateurs", "blazorgame");

                    b.HasData(
                        new
                        {
                            administrateurid = 50,
                            utilisateurId = 40
                        });
                });

            modelBuilder.Entity("SharedModels.Donjons", b =>
                {
                    b.Property<int>("donjonsid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("donjonsid"));

                    b.HasKey("donjonsid");

                    b.ToTable("Donjons", "blazorgame");
                });

            modelBuilder.Entity("SharedModels.Joueur", b =>
                {
                    b.Property<int>("joueurid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("joueurid"));

                    b.Property<int>("utilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("joueurid");

                    b.HasIndex("utilisateurId")
                        .IsUnique();

                    b.ToTable("Joueurs", "blazorgame");

                    b.HasData(
                        new
                        {
                            joueurid = 20,
                            utilisateurId = 20
                        });
                });

            modelBuilder.Entity("SharedModels.Monstre", b =>
                {
                    b.Property<int>("monstreid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("monstreid"));

                    b.Property<double>("chanceToucher")
                        .HasColumnType("double precision");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("lienImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("pointDeVie")
                        .HasColumnType("integer");

                    b.Property<double>("pointGagner")
                        .HasColumnType("double precision");

                    b.HasKey("monstreid");

                    b.ToTable("Monstres", "blazorgame");

                    b.HasData(
                        new
                        {
                            monstreid = 1,
                            chanceToucher = 30.5,
                            description = "Alien venu de l'univers pour enlever une princesse sur la planète terre. Extrêment rapide mais faible",
                            lienImage = "alien.jpeg",
                            nom = "tatunga",
                            pointDeVie = 9,
                            pointGagner = 4.5
                        },
                        new
                        {
                            monstreid = 2,
                            chanceToucher = 90.5,
                            description = "Cambrioleur qui cambriole des donjons, précis mais lent",
                            lienImage = "cambrioleur.png",
                            nom = "Cambrioleur",
                            pointDeVie = 20,
                            pointGagner = 45.0
                        },
                        new
                        {
                            monstreid = 3,
                            chanceToucher = 10.5,
                            description = "Empereur ayant la volonté d'assujetir la terre, TRES résistant mais vise très mal. Vous devriez fuir le combat",
                            lienImage = "empereur_espace.jpg",
                            nom = "empereur_de_lespace",
                            pointDeVie = 100,
                            pointGagner = 450.0
                        },
                        new
                        {
                            monstreid = 4,
                            chanceToucher = 100.0,
                            description = "Enfant s'étant perdu dans le donjon, très facile à battre et donne beaucoup d'expérience. Mais franchement, qui serait assez cruel pour se battre avec un enfant ?",
                            lienImage = "garcon_effrayant.jpg",
                            nom = "garçon_effrayant",
                            pointDeVie = 1,
                            pointGagner = 500.0
                        },
                        new
                        {
                            monstreid = 5,
                            chanceToucher = 90.0,
                            description = "Juste un type avec un flingue, le frapper sera facile et pour vous et pour lui",
                            lienImage = "homme_avec_une_arme.jpeg",
                            nom = "Homme avec une arme",
                            pointDeVie = 40,
                            pointGagner = 290.0
                        },
                        new
                        {
                            monstreid = 6,
                            chanceToucher = 70.0,
                            description = "Le pire ennemi de tout le monde, entrainé par des années d'attaque de mauvais payeurs, il n'aura aucun mal à vous rendre la monnaie de votre pièce",
                            lienImage = "inspecteur_impot.jpg",
                            nom = "inspecteur_impot",
                            pointDeVie = 35,
                            pointGagner = 100.0
                        },
                        new
                        {
                            monstreid = 7,
                            chanceToucher = 60.0,
                            description = "Mechant qui veut tuer la gentille parce que c'est le méchant ni plus ni moins",
                            lienImage = "mechant_qui_veut_tuer_la_gentille.png",
                            nom = "mechant_qui_veut_tuer_la_gentille",
                            pointDeVie = 40,
                            pointGagner = 200.0
                        },
                        new
                        {
                            monstreid = 8,
                            chanceToucher = 50.0,
                            description = "Souris qui aime beaucoup noel, avec lui c'est 50/50",
                            lienImage = "mickey_mouse.gif",
                            nom = "mickey_mouse",
                            pointDeVie = 50,
                            pointGagner = 500.0
                        },
                        new
                        {
                            monstreid = 9,
                            chanceToucher = 20.0,
                            description = "Homme très violent et ératique. Mieux vaux ne pas l'énerver",
                            lienImage = "mister_frog.jpeg",
                            nom = "Mister Frog",
                            pointDeVie = 200,
                            pointGagner = 500.0
                        },
                        new
                        {
                            monstreid = 10,
                            chanceToucher = 70.0,
                            description = "WAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALUIGI TIME!!!!!!!!!!!!!!!!!!",
                            lienImage = "waluigi.jpg",
                            nom = "waluigi",
                            pointDeVie = 70,
                            pointGagner = 190.0
                        });
                });

            modelBuilder.Entity("SharedModels.Salles", b =>
                {
                    b.Property<int>("salleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("salleId"));

                    b.Property<int>("monstreId")
                        .HasColumnType("integer");

                    b.Property<double>("scoreBonus")
                        .HasColumnType("double precision");

                    b.HasKey("salleId");

                    b.HasIndex("monstreId")
                        .IsUnique();

                    b.ToTable("Salles", "blazorgame");

                    b.HasData(
                        new
                        {
                            salleId = 10,
                            monstreId = 1,
                            scoreBonus = 230.0
                        },
                        new
                        {
                            salleId = 20,
                            monstreId = 2,
                            scoreBonus = -300.0
                        },
                        new
                        {
                            salleId = 30,
                            monstreId = 3,
                            scoreBonus = 400.0
                        },
                        new
                        {
                            salleId = 40,
                            monstreId = 4,
                            scoreBonus = -230.0
                        },
                        new
                        {
                            salleId = 50,
                            monstreId = 5,
                            scoreBonus = 90.0
                        },
                        new
                        {
                            salleId = 60,
                            monstreId = 6,
                            scoreBonus = 230.0
                        },
                        new
                        {
                            salleId = 70,
                            monstreId = 7,
                            scoreBonus = 10.0
                        },
                        new
                        {
                            salleId = 80,
                            monstreId = 8,
                            scoreBonus = -30.0
                        },
                        new
                        {
                            salleId = 90,
                            monstreId = 9,
                            scoreBonus = -247.0
                        },
                        new
                        {
                            salleId = 100,
                            monstreId = 10,
                            scoreBonus = -300.0
                        });
                });

            modelBuilder.Entity("SharedModels.ScorePartie", b =>
                {
                    b.Property<int>("ScorePartieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScorePartieId"));

                    b.Property<int>("degatsInfliges")
                        .HasColumnType("integer");

                    b.Property<int>("donjonId")
                        .HasColumnType("integer");

                    b.Property<int>("joueurId")
                        .HasColumnType("integer");

                    b.Property<bool>("partieTerminee")
                        .HasColumnType("boolean");

                    b.Property<int>("pointsDeVie")
                        .HasColumnType("integer");

                    b.Property<int>("progression")
                        .HasColumnType("integer");

                    b.Property<double>("score")
                        .HasColumnType("double precision");

                    b.HasKey("ScorePartieId");

                    b.HasIndex("donjonId")
                        .IsUnique();

                    b.HasIndex("joueurId");

                    b.ToTable("ScoreParties", "blazorgame");
                });

            modelBuilder.Entity("SharedModels.Utilisateur", b =>
                {
                    b.Property<int>("utilisateurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("utilisateurId"));

                    b.Property<string>("adresseMail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("estActive")
                        .HasColumnType("boolean");

                    b.Property<string>("motDePasse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("utilisateurId");

                    b.ToTable("Utilisateurs", "blazorgame");

                    b.HasData(
                        new
                        {
                            utilisateurId = 20,
                            adresseMail = "Test@Test.com",
                            estActive = true,
                            motDePasse = "Test",
                            nom = "Test",
                            prenom = "Test"
                        },
                        new
                        {
                            utilisateurId = 40,
                            adresseMail = "testadmin@admin.com",
                            estActive = true,
                            motDePasse = "Admin",
                            nom = "Admin",
                            prenom = "DeTest"
                        });
                });

            modelBuilder.Entity("DonjonsSalles", b =>
                {
                    b.HasOne("SharedModels.Donjons", null)
                        .WithMany()
                        .HasForeignKey("donjonsListdonjonsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedModels.Salles", null)
                        .WithMany()
                        .HasForeignKey("sallesListsalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharedModels.Administrateur", b =>
                {
                    b.HasOne("SharedModels.Utilisateur", "utilisateur")
                        .WithOne("administrateur")
                        .HasForeignKey("SharedModels.Administrateur", "utilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("utilisateur");
                });

            modelBuilder.Entity("SharedModels.Joueur", b =>
                {
                    b.HasOne("SharedModels.Utilisateur", "utilisateur")
                        .WithOne("joueur")
                        .HasForeignKey("SharedModels.Joueur", "utilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("utilisateur");
                });

            modelBuilder.Entity("SharedModels.Salles", b =>
                {
                    b.HasOne("SharedModels.Monstre", "monstre")
                        .WithOne("salle")
                        .HasForeignKey("SharedModels.Salles", "monstreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("monstre");
                });

            modelBuilder.Entity("SharedModels.ScorePartie", b =>
                {
                    b.HasOne("SharedModels.Donjons", "donjonGenere")
                        .WithOne("scorePartie")
                        .HasForeignKey("SharedModels.ScorePartie", "donjonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedModels.Joueur", "joueur")
                        .WithMany("score")
                        .HasForeignKey("joueurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("donjonGenere");

                    b.Navigation("joueur");
                });

            modelBuilder.Entity("SharedModels.Donjons", b =>
                {
                    b.Navigation("scorePartie");
                });

            modelBuilder.Entity("SharedModels.Joueur", b =>
                {
                    b.Navigation("score");
                });

            modelBuilder.Entity("SharedModels.Monstre", b =>
                {
                    b.Navigation("salle");
                });

            modelBuilder.Entity("SharedModels.Utilisateur", b =>
                {
                    b.Navigation("administrateur");

                    b.Navigation("joueur");
                });
#pragma warning restore 612, 618
        }
    }
}
