DROP DATABASE IF EXISTS "User";
DROP ROLE IF EXISTS "UserUser";
CREATE ROLE "UserUser";
ALTER ROLE "UserUser" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN PASSWORD 'userDBpassword';
CREATE DATABASE "User";
ALTER DATABASE "User" OWNER TO "UserUser";
      
DROP DATABASE IF EXISTS "Score";
DROP ROLE IF EXISTS "ScoreUser";
CREATE ROLE "ScoreUser";
ALTER ROLE "ScoreUser" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN PASSWORD 'scoreDBpassword';
CREATE DATABASE "Score";
ALTER DATABASE "Score" OWNER TO "ScoreUser";
      
DROP DATABASE IF EXISTS "Game";
DROP ROLE IF EXISTS "GameUser";
CREATE ROLE "GameUser";
ALTER ROLE "GameUser" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN PASSWORD 'GameDBpassword';
CREATE DATABASE "Game";
ALTER DATABASE "Game" OWNER TO "GameUser";