syntax = "proto3";

option csharp_namespace = "User";

package UserService;

// The greeting service definition.
service UserService {
  // Sends a greeting
  rpc CreateUser(CreateUserRequest) returns (UserResponse);
  rpc GetUser(GetUserRequest) returns (UserResponse);
  rpc UpdateUser(UpdateUserRequest) returns (UserResponse);
  rpc DeleteUser(DeleteUserRequest) returns (OkResponse);
  
}

message CreateUserRequest
{
  string pseudo = 1;  
}

message GetUserRequest
{
  int32 user_id = 1;
}

message UpdateUserRequest
{
  int32 user_id = 1;
  string pseudo = 2;
}

message DeleteUserRequest
{
  int32 user_id = 1;
}

message UserResponse 
{
  int32 user_id = 1;
  string pseudo = 2;
}

message OkResponse
{
}
